/* eslint-disable @typescript-eslint/no-unnecessary-condition */
import { useEffect,useState } from "react"
import { Link,useParams } from "@tanstack/react-router"
import { Printer } from "lucide-react"
import { fetchDocument,type CentralDocument } from "@/lib/platform/api"
import { Button } from "@/shared/components/ui/button"
import { Separator } from "@/shared/components/ui/separator"
import { formatCurrency,formatDate } from "@/shared/utils"
export function DocumentViewPage(){const{id}=useParams({from:"/app/documents/$id"});const[document,setDocument]=useState<CentralDocument>()
 useEffect(()=>{void fetchDocument(id).then((result)=>{setDocument(result.document)})},[id]);if(!document)return <p className="p-6 text-muted-foreground">جاري تحميل المستند...</p>
 const seller=document.organization_snapshot as {business_name?:string;vat_number?:string};const customer=document.customer_snapshot
 return <div className="min-h-screen bg-muted/20 p-3 sm:p-6" dir="rtl"><div className="mx-auto mb-3 flex max-w-4xl justify-between print:hidden"><Link to="/documents" className="text-sm text-muted-foreground">العودة للفواتير</Link><Button variant="outline" className="gap-2" onClick={()=>{window.print()}}><Printer className="size-4"/>طباعة / PDF</Button></div><article className="mx-auto max-w-4xl rounded-xl border bg-white p-5 shadow-sm sm:p-8 print:border-0 print:shadow-none"><header className="flex justify-between gap-4"><div><h1 className="text-2xl font-bold">فاتورة ضريبية</h1><p className="font-mono text-primary">{document.status==="draft"?"مسودة غير صادرة":document.number}</p></div><div className="text-end text-sm"><p>{formatDate(document.issue_date)}</p><p className="text-muted-foreground">{document.status==="issued"?"صادرة":"مسودة"}</p></div></header><Separator className="my-5"/><section className="grid gap-5 text-sm sm:grid-cols-2"><div><p className="text-xs text-muted-foreground">من</p><p className="font-semibold">{seller.business_name??"—"}</p><p dir="ltr">{seller.vat_number??""}</p></div><div><p className="text-xs text-muted-foreground">إلى</p><p className="font-semibold">{customer?.name??"—"}</p><p dir="ltr">{customer?.vat_number??""}</p><p>{[customer?.street,customer?.building_number,customer?.district,customer?.city,customer?.postal_code].filter(Boolean).join("، ")}</p></div></section><div className="my-6 overflow-x-auto"><table className="w-full min-w-[560px] text-sm"><thead><tr className="border-b bg-muted/30"><th className="p-2 text-start">البيان</th><th>الكمية</th><th>السعر</th><th>الضريبة</th><th className="text-end">الإجمالي</th></tr></thead><tbody>{document.items?.map((item)=><tr key={item.id} className="border-b"><td className="p-2">{item.description}</td><td className="text-center">{item.quantity}</td><td className="text-center">{formatCurrency(Number(item.unit_price))}</td><td className="text-center">{formatCurrency(Number(item.line_tax))}</td><td className="text-end">{formatCurrency(Number(item.line_total))}</td></tr>)}</tbody></table></div><div className="ms-auto max-w-sm space-y-2 text-sm"><Row label="المجموع قبل الضريبة" value={Number(document.subtotal)}/><Row label="ضريبة القيمة المضافة 15%" value={Number(document.tax_total)}/>{Number(document.retention_total)>0?<Row label="ضمان الأعمال" value={-Number(document.retention_total)}/>:null}<Separator/><Row label="الإجمالي" value={Number(document.total)} bold/></div>{document.notes?<div className="mt-6 border-t pt-4"><p className="font-medium">ملاحظات</p><p className="whitespace-pre-wrap text-sm text-muted-foreground">{document.notes}</p></div>:null}</article></div>}
function Row({label,value,bold=false}:{label:string;value:number;bold?:boolean}){return <div className={`flex justify-between ${bold?"text-base font-bold":""}`}><span>{label}</span><span>{formatCurrency(value)}</span></div>}
