import { useEffect, useState, type Dispatch, type SetStateAction } from "react"
import { Trash2 } from "lucide-react"
import { deleteBrandingAsset, fetchBrandingAssetUrl, uploadBrandingAsset, type BrandingAssetKind } from "@/lib/platform/api"
import { Button } from "@/shared/components/ui/button"
import { Input } from "@/shared/components/ui/input"
import { toast } from "@/shared/hooks/useToast"
import type { Form } from "../pages/SettingsPage"

export function BrandingSettings({ form, setForm }: { form: Form; setForm: Dispatch<SetStateAction<Form | null>> }) {
  const [urls, setUrls] = useState<Partial<Record<BrandingAssetKind, string>>>({})
  const [busy, setBusy] = useState<BrandingAssetKind>()
  useEffect(() => { void Promise.all((["logo", "stamp", "signature"] as const).map(async (kind) => { const url = await fetchBrandingAssetUrl(kind); if (url) setUrls((current) => ({ ...current, [kind]: url })) })) }, [])
  const upload = async (kind: BrandingAssetKind, file: File) => { setBusy(kind); try { await uploadBrandingAsset(kind, file); setUrls((current) => ({ ...current, [kind]: URL.createObjectURL(file) })); setForm((current) => current ? { ...current, [`${kind}_url`]: "stored" } : current); toast({ title: "تم رفع الملف", variant: "success" }) } catch (error) { toast({ title: "تعذر رفع الملف", description: error instanceof Error ? error.message : "حاول مرة أخرى", variant: "error" }) } finally { setBusy(undefined) } }
  const remove = async (kind: BrandingAssetKind) => { setBusy(kind); try { await deleteBrandingAsset(kind); setUrls((current) => ({ ...current, [kind]: undefined })); setForm((current) => current ? { ...current, [`${kind}_url`]: null, ...(kind === "stamp" ? { stamp_on_invoice:false, stamp_on_quotation:false, stamp_on_receipt:false } : kind === "signature" ? { signature_on_invoice:false, signature_on_quotation:false, signature_on_receipt:false } : {}) } : current) } finally { setBusy(undefined) } }
  const toggle = (key: string, value: boolean) => { setForm((current) => current ? { ...current, [key]: value } : current) }
  return <><h2 className="text-lg font-semibold">الهوية البصرية والمستندات</h2><p className="text-sm text-muted-foreground">ملفات PNG فقط وبحجم أقصى 2MB. لا تظهر مساحة فارغة عند عدم رفع الملف.</p>{(["logo", "stamp", "signature"] as const).map((kind) => <section key={kind} className="space-y-3 rounded-xl border p-4"><div><h3 className="font-medium">{{logo:"شعار المنشأة",stamp:"ختم المنشأة",signature:"توقيع المنشأة"}[kind]}</h3><p className="text-xs text-muted-foreground">{kind === "logo" ? "يظهر في جميع المستندات الصادرة." : "اختياري ويمكن تحديد المستندات التي يظهر فيها."}</p></div>{urls[kind] ? <div className="flex flex-wrap items-center gap-4"><img src={urls[kind]} alt={kind} className="h-24 w-40 rounded-lg border bg-white object-contain p-2"/><Button type="button" variant="outline" disabled={busy===kind} onClick={()=>{void remove(kind)}} className="gap-2"><Trash2 className="size-4"/>حذف</Button></div> : <Input type="file" accept="image/png" disabled={busy===kind} onChange={(event)=>{const file=event.target.files?.[0];if(file)void upload(kind,file)}}/>}{kind !== "logo" && urls[kind] ? <div className="grid gap-2 sm:grid-cols-3">{(["invoice","quotation","receipt"] as const).map((documentType)=><label key={documentType} className="flex items-center gap-2 rounded-lg border p-3 text-sm"><input type="checkbox" checked={Boolean(form[`${kind}_on_${documentType}`])} onChange={(event)=>{toggle(`${kind}_on_${documentType}`,event.target.checked)}}/><span>{{invoice:"الفاتورة الضريبية",quotation:"عرض السعر",receipt:"سند القبض"}[documentType]}</span></label>)}</div> : null}</section>)}</>
}
