import { useEffect,useMemo,useState } from "react"
import { Building2,Edit2,Mail,MapPin,Phone,Plus,Search,Trash2 } from "lucide-react"
import { listCustomers,type CentralCustomer } from "@/lib/platform/api"
import { Button } from "@/shared/components/ui/button"
import { Input } from "@/shared/components/ui/input"
import { toast } from "@/shared/hooks/useToast"
import { CustomerDialog } from "../components/CustomerDialog"
import { CustomerDeleteDialog } from "../components/CustomerDeleteDialog"
import { CustomerAccountDialog } from "../components/CustomerAccountDialog"
export default function CustomersPage(){const[customers,setCustomers]=useState<CentralCustomer[]>([]),[search,setSearch]=useState(""),[loading,setLoading]=useState(true),[add,setAdd]=useState(false),[edit,setEdit]=useState<CentralCustomer>(),[remove,setRemove]=useState<CentralCustomer|null>(null),[account,setAccount]=useState<CentralCustomer>()
 useEffect(()=>{void listCustomers().then((r)=>{ setCustomers(r.customers); }).catch((error:unknown)=>{ toast({title:"تعذر تحميل العملاء",description:error instanceof Error?error.message:"حاول مرة أخرى",variant:"error"}); }).finally(()=>{ setLoading(false); })},[])
 const shown=useMemo(()=>customers.filter((c)=>!search||c.name.includes(search)||c.vat_number.includes(search)||(c.phone??"").includes(search)),[customers,search]);const save=(c:CentralCustomer)=>{ setCustomers((all)=>[...all.filter((x)=>x.id!==c.id),c].sort((a,b)=>a.name.localeCompare(b.name,"ar"))); }
 return <div className="space-y-5 p-4 sm:p-6" dir="rtl"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">العملاء</h1><p className="text-sm text-muted-foreground">{customers.length} عميل محفوظ مركزيًا</p></div><Button className="gap-2" onClick={()=>{ setAdd(true); }}><Plus className="size-4"/>عميل جديد</Button></div>
 <div className="relative max-w-md"><Search className="absolute start-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input className="ps-9" placeholder="ابحث بالاسم أو الرقم الضريبي أو الجوال" value={search} onChange={(e)=>{ setSearch(e.target.value); }}/></div>
 {loading?<p className="py-20 text-center text-muted-foreground">جاري تحميل العملاء...</p>:shown.length?<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{shown.map((c)=><article key={c.id} className="rounded-xl border bg-card p-4"><div className="flex justify-between gap-3"><div><h2 className="font-semibold">{c.name}</h2><p className="text-xs text-muted-foreground" dir="ltr">{c.vat_number}</p></div><div className="flex gap-1"><button aria-label="تعديل" className="rounded p-2 hover:bg-muted" onClick={()=>{ setEdit(c); }}><Edit2 className="size-4"/></button><button aria-label="حذف" className="rounded p-2 hover:bg-destructive/10" onClick={()=>{ setRemove(c); }}><Trash2 className="size-4"/></button></div></div><div className="mt-3 space-y-1 border-t pt-3 text-xs text-muted-foreground">{c.phone&&<p className="flex gap-2"><Phone className="size-3"/>{c.phone}</p>}{c.email&&<p className="flex gap-2"><Mail className="size-3"/>{c.email}</p>}<p className="flex gap-2"><MapPin className="size-3"/>{c.city}، {c.district}، {c.street}، {c.building_number}</p></div><Button type="button" variant="outline" className="mt-4 w-full" onClick={()=>{setAccount(c)}}>عرض حساب العميل</Button></article>)}</div>:<div className="py-24 text-center text-muted-foreground"><Building2 className="mx-auto mb-3 size-14 opacity-20"/><p>لا يوجد عملاء بعد</p></div>}
 <CustomerDialog open={add} onClose={()=>{ setAdd(false); }} onSaved={save}/>{edit&&<CustomerDialog open onClose={()=>{ setEdit(undefined); }} customer={edit} onSaved={save}/>}<CustomerDeleteDialog customer={remove} onClose={()=>{ setRemove(null); }} onDeleted={(id)=>{ setCustomers((all)=>all.filter((c)=>c.id!==id)); }}/>{account?<CustomerAccountDialog customer={account} onClose={()=>{setAccount(undefined)}}/>:null}</div>}
