import { useEffect, useMemo, useState } from "react"
import { Plus, Search } from "lucide-react"
import { createCustomer, listCustomers, type CentralCustomer, type CustomerInput } from "@/lib/platform/api"
import { Button } from "@/shared/components/ui/button"
import { Input } from "@/shared/components/ui/input"
import { Label } from "@/shared/components/ui/label"
import { toast } from "@/shared/hooks/useToast"

interface CustomerFields { customer_id:string; customer_name:string; customer_vat_number:string; customer_phone:string; customer_email:string; customer_address:string }
const empty:CustomerInput={name:"",vat_number:"",city:"",district:"",street:"",building_number:"",postal_code:""}

export function CustomerSelector({values,onChange}:{values:CustomerFields;onChange:(fields:Partial<CustomerFields>)=>void}){
 const[customers,setCustomers]=useState<CentralCustomer[]>([]);const[search,setSearch]=useState("");const[open,setOpen]=useState(false);const[adding,setAdding]=useState(false);const[saving,setSaving]=useState(false);const[customer,setCustomer]=useState<CustomerInput>(empty)
 useEffect(()=>{void listCustomers().then((result)=>{ setCustomers(result.customers); })},[])
 const filtered=useMemo(()=>customers.filter((item)=>!search||item.name.includes(search)||item.vat_number.includes(search)),[customers,search])
 const select=(item:CentralCustomer)=>{onChange({customer_id:item.id,customer_name:item.name,customer_vat_number:item.vat_number,customer_phone:item.phone??"",customer_email:item.email??"",customer_address:[item.street,item.building_number,item.district,item.city,item.postal_code].filter(Boolean).join("، ")});setSearch("");setOpen(false);setAdding(false)}
 const set=(key:keyof CustomerInput,value:string)=>{ setCustomer((current)=>({...current,[key]:value})); }
 const save=async()=>{setSaving(true);try{const result=await createCustomer(customer);setCustomers((current)=>[...current,result.customer]);select(result.customer);setCustomer(empty);toast({title:"تمت إضافة العميل",variant:"success"})}catch(error){toast({title:"تعذر إضافة العميل",description:error instanceof Error?error.message:"راجع البيانات",variant:"error"})}finally{setSaving(false)}}
 return <div className="space-y-3"><div className="space-y-1.5"><Label>العميل *</Label><div className="relative"><Search className="absolute start-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input className="ps-9" placeholder="ابحث بالاسم أو الرقم الضريبي" value={open?search:values.customer_name} onFocus={()=>{setOpen(true);setSearch("")}} onChange={(event)=>{setSearch(event.target.value);setOpen(true)}}/>{open&&!adding?<div className="absolute z-20 mt-1 max-h-52 w-full overflow-auto rounded-md border bg-popover shadow-lg">{filtered.map((item)=><button type="button" key={item.id} className="block w-full border-b px-3 py-2 text-start hover:bg-accent" onMouseDown={()=>{ select(item); }}><span className="block text-sm font-medium">{item.name}</span><span className="text-xs text-muted-foreground" dir="ltr">{item.vat_number}</span></button>)}<button type="button" className="flex w-full items-center gap-2 px-3 py-3 text-sm font-medium text-primary hover:bg-accent" onMouseDown={()=>{setAdding(true);setOpen(false)}}><Plus className="size-4"/>إضافة عميل جديد</button></div>:null}</div></div>
 {adding?<div className="space-y-3 rounded-lg border bg-muted/20 p-4"><p className="font-medium">إضافة عميل جديد</p><div className="grid gap-3 sm:grid-cols-2"><Input placeholder="اسم العميل *" value={customer.name} onChange={(e)=>{ set("name",e.target.value); }}/><Input placeholder="الرقم الضريبي (15 رقمًا) *" dir="ltr" value={customer.vat_number} onChange={(e)=>{ set("vat_number",e.target.value); }}/><Input placeholder="المدينة *" value={customer.city} onChange={(e)=>{ set("city",e.target.value); }}/><Input placeholder="الحي *" value={customer.district} onChange={(e)=>{ set("district",e.target.value); }}/><Input placeholder="الشارع *" value={customer.street} onChange={(e)=>{ set("street",e.target.value); }}/><Input placeholder="رقم المبنى (4 أرقام) *" dir="ltr" value={customer.building_number} onChange={(e)=>{ set("building_number",e.target.value); }}/><Input placeholder="الرمز البريدي (5 أرقام) *" dir="ltr" value={customer.postal_code} onChange={(e)=>{ set("postal_code",e.target.value); }}/><Input placeholder="رقم الجوال" dir="ltr" value={customer.phone??""} onChange={(e)=>{ set("phone",e.target.value); }}/><Input placeholder="البريد الإلكتروني" dir="ltr" value={customer.email??""} onChange={(e)=>{ set("email",e.target.value); }}/></div><div className="flex gap-2"><Button type="button" loading={saving} onClick={()=>void save()}>حفظ واختيار العميل</Button><Button type="button" variant="ghost" onClick={()=>{ setAdding(false); }}>إلغاء</Button></div></div>:null}
 {values.customer_id?<div className="rounded-lg bg-muted/40 p-3 text-sm"><p className="font-medium">{values.customer_name}</p><p className="text-muted-foreground" dir="ltr">{values.customer_vat_number}</p><p className="text-muted-foreground">{values.customer_address}</p></div>:null}</div>
}
